### ISSUE TITLE
Get not compressed data and reconstruction

### ISSUE THREAD

**Issue by htian97** [steineggerlab/foldcomp#11]
First of all, very nice work!
From my understanding, the workflow is PDB -> internal coordinates -> compress -> decompress -> reconstruction. I'm wondering how can I use the existing APIs to skip the compress -> decompress step, and just have internal coordinates -> reconstruction. Thanks!

**Comment by khb7840** [comment]
In C++ lib, we have NeRF module for conducting reconstruction with inner coordinates. What is the format of the inner coordinates? If you're working in python, we can add NeRF to our python API.

**Comment by htian97** [comment]
I'm not familiar with C++ binding with Python. I played around with the Python APIs. I found out that currently it's not something like we need to first have an instance of `foldcomp` class storing all the intermediate data, but instead all functions are static. Is it easy in terms of implementation that we can do something like:

```python
foldcomp = foldcomp.Foldcomp()
foldcomp.preprocess(PDB_FILE)
print(foldcomp.inner_coordinates)
# use inner coordinates to reconstruct 3d structure
new_structure = foldcomp.reconstruct()
```

**Comment by htian97** [comment]
I found a Matlab script for NeRF: https://github.com/gtamazian/PROMPT/blob/master/restorecoords.m. 
What's the main difference between this script and foldcomp package?

**Comment by martin-steinegger** [comment]
There are plenty of NeRF implementations in all kinds of languages. NeRF is just one part of foldcomp how to reconstruct the structures. Additionally, foldcomp performs forward/backward averaging and anchors to reduce reconstruction error. Also, our format to store protein structures is optimized to require minimal bits.
