### ISSUE TITLE
Can foldseek database be built from fcz files?

### ISSUE THREAD

**Issue by yakomaxa** [steineggerlab/foldcomp#15]
I have a set of fcz files and made a custom FoldComp database by the protocol thankfully described here: https://github.com/steineggerlab/foldcomp/issues/14

Next, I would like to search the structures using FoldSeek. I guess one obvious solution would be just dumping the PDB/mmCIF files from FoldComp and converting them into FoldSeek database. 

However, are there more direct ways to build FoldSeek database from FoldComp-related dataset? It could be nice if we can build FoldSeek database without de-compressing the FoldComp-related files.

Thank you again for excellent softwares!

**Comment by khb7840** [comment]
Currently we don't have direct conversion features for Foldseek, but we have a plan to develop Foldseek to support Foldcomp databases (and fcz file format). As your suggestion, we would add some direct conversion features for various formats, including saving only Ca coordinates (current Foldseek DB). Thanks for your interests! We'll try to update Foldcomp with more features soon :)

**Comment by yakomaxa** [comment]
Thank you for explaining the current status and future plans. Although it's not a big problem to decompress fcz files (or whole FoldComp db) into pdb files because it's just temporary, it would be helpful if FoldSeek is made possible to directly read them.  

Your softwares are so fascinating. I guess fcz format will be a standard format for large structure databases. 

I'm looking forward to seeing further development of FoldComp and FoldSeek!

**Comment by milot-mirdita** [comment]
The latest git version contains code to build foldcomp databases directly within foldcomp.

You can pass the `--db` flag to the command line util to build a foldcomp database.

**Comment by SIITW** [comment]
> Thank you for developing and announcing this function. I've successfully constructed a foldseek database from my custom foldcomp database. It works nicely at this moment.

Hello, how do you do it, how did you convert FoldComp to FoldSeek database?
