### ISSUE TITLE
[Bug] Garbage collection when opening a database multiple times

### ISSUE THREAD

**Issue by Oxer11** [steineggerlab/foldcomp#25]
Hi, thanks for the great work! I've faced an OOM issue with python when loading pdbs from a preprocessed database multiple times. So I write the following simple test codes:
```python
import os
import sys
import psutil
import foldcomp

with open("afdb_rep_v4.lookup", "r") as f:
  lines = f.readlines()
  ids = [line.strip().split("\t")[1] for line in lines]

batch_size = 1000
for i in range(0, len(ids), batch_size):
  with foldcomp.open("afdb_rep_v4", ids=ids[i:i+batch_size]) as db:
    for (name, pdb) in db:
      pass
    print(psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024, "MB")
```

I get the following output:
```
883.08203125 MB
1034.078125 MB
1199.5390625 MB
1382.18359375 MB
1569.828125 MB
1753.88671875 MB
1913.41796875 MB
2077.76953125 MB
2258.7734375 MB
2381.3046875 MB
2503.25390625 MB
2673.3515625 MB
2807.8671875 MB
...
```

The memory used by the program continues to increase. This suggests that some variables are not freed after closing the database. Besides, when deleting the for loop `for (name, pdb) in db:`, the memory issue will be solved. So I'm wondering whether there are some problems in the garbage collection process of `FoldcompDatabase`.

**Comment by khb7840** [comment]
Hi @Oxer11,
Thank you for bringing this issue to our attention. 
I have checked the error and it seems to be related with decompression while iterating database. 
We're going to work on a fix for this issue.
Thanks again for your help.

**Comment by khb7840** [comment]
We've fixed memory leakage in the latest release. Thank you for raising this issue.
