### ISSUE TITLE
decompress a subset of entries

### ISSUE THREAD

**Issue by kad-ecoli** [steineggerlab/foldcomp#27]
Is it possible to extract the pdb files for a subset of entries from a folcomp database. I am looking for something like this:

```bash
foldcomp decompress --subset id_list.txt afdb_uniprot_v4 
```
where id_list.txt list a subset of entries in afdb_uniprot_v4, one entry per line.

**Comment by martin-steinegger** [comment]
yes I totally agree that this would be great. @khb7840 yes we want this! Didn't we built something similar?

**Comment by kad-ecoli** [comment]
I see that README.md suggest using mmseqs to subset database. Unfortunately, that does not work, as reported by issue 
https://github.com/steineggerlab/foldcomp/issues/28

**Comment by khb7840** [comment]
This feature is now available in the latest version as:
```sh
foldcomp decompress --id-list id_list.txt afdb_uniprot_v4
```
