### ISSUE TITLE
subset does not work

### ISSUE THREAD

**Issue by kad-ecoli** [steineggerlab/foldcomp#28]
The procedure described in https://github.com/steineggerlab/foldcomp#subsetting-databases actually breaks the database.
As an example, try to get the first 10 structures of the H sapiens proteome:
```bash
$ grep -ohP "\S+.pdb" h_sapiens.lookup |head > id_list.txt
$ mmseqs createsubdb --subdb-mode 0 --id-mode 1 id_list.txt h_sapiens h_sapiens_subset
$ foldcomp decompress h_sapiens_subset

Decompressing files in h_sapiens_subset using 1 threads
Output directory: h_sapiens_subset_pdb/
foldcomp: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned l
```

This is related to issue https://github.com/steineggerlab/foldcomp/issues/27

**Comment by khb7840** [comment]
We've fixed this error in the latest release. Thank you for notifying this.
