### ISSUE TITLE
bug in bfactor field of OXT atom

### ISSUE THREAD

**Issue by kad-ecoli** [steineggerlab/foldcomp#30]
It seems foldcomp does not correctly recover the bfactor field for the last atom (OXT). For example, in AF-A0A021WW32-F1-model_v4.pdb decompress from afdb_uniprot_v4, the last line is
```
ATOM   4965  OXT HIS A 633      -7.060 -30.397  50.703  1.00  0.00           O
```
However, the bfactor of this atom should have been 43.28 according to https://alphafold.ebi.ac.uk/entry/A0A021WW32

**Comment by khb7840** [comment]
This is fixed in the latest commit
