### ISSUE TITLE
Extracting sequences from Foldcomp database

### ISSUE THREAD

**Issue by valentynbez** [steineggerlab/foldcomp#34]
Hello, 

First of all, thank you for amazing library! 
Is there a way to extract sequences from the database? It is possible to retrieve with Python interface, but it is too slow in my case. 
CLI doesn't allow me to do it, I receive errors:
```
 ./foldcomp extract --fasta -t 16 afdb_swissprot_v4 fasta_test        
```
```
[Error] processing db entry AF-P80216-F1-model_v4
[Error] processing db entry AF-B7J2B3-F1-model_v4 failed.AF-P02460-F1-model_v4 failed.
[Error] File is not a valid fcz file
AF-Q8LBQ7-F1-model_v4 failed.
```

Any advice on how to extract sequences more efficiently?

**Comment by khb7840** [comment]
I'm looking into the error. Thank you for raising this issue 😄

**Comment by khb7840** [comment]
Could you try with latest version? Because I didn't get the error from your command with `afdb_swissprot_v4`

**Comment by valentynbez** [comment]
I built from latest github source using `build.sh`. I used it on `afdb_swissprot_v4` downloaded from the lab and ran: 
`./foldcomp extract --fasta -t 16 afdb_swissprot_v4 fasta_test`
Receiving same errors:
```
[Error] File is not a valid fcz file
[Error] processing db entry AF-Q2S902-F1-model_v4 failed.
[Error] File is not a valid fcz file
```

**Comment by milot-mirdita** [comment]
Could you compute md5sums for the various `afdb_swissprot_v4*` files?

I'll compute the expected md5 sums tomorrow and post them here.

**Comment by valentynbez** [comment]
Sure! 
```
1cfbec179a06f0fbba0a8f7880713098  afdb_swissprot_v4
740bab4f9ec8808aedb68d6b1281aeb2  afdb_swissprot_v4.dbtype
05e8b8fba2544b88f9188e1eb1131d8a  afdb_swissprot_v4.index
3a1da264a0877bf142e134a6c0f00d4a  afdb_swissprot_v4.lookup
61ffaa1f49241f9ddce58a0d2872dccd  afdb_swissprot_v4.source
```

**Comment by khb7840** [comment]
It seems like the database file is different from the released one. Please check with [this file](https://foldcomp.steineggerlab.workers.dev/afdb_swissprot_v4) or you may download the db with python api as `foldcomp.setup("afdb_swissprot_v4")`

```
00aa35452babd2b20b4df01264eac860  afdb_swissprot_v4
740bab4f9ec8808aedb68d6b1281aeb2  afdb_swissprot_v4.dbtype
05e8b8fba2544b88f9188e1eb1131d8a  afdb_swissprot_v4.index
3a1da264a0877bf142e134a6c0f00d4a  afdb_swissprot_v4.lookup
61ffaa1f49241f9ddce58a0d2872dccd  afdb_swissprot_v4.source
```

**Comment by valentynbez** [comment]
Hello, @khb7840!
You're right, it looks like something went wrong during the download. Everything works fine now, thanks for support!
