### ISSUE TITLE
Merging databases

### ISSUE THREAD

**Issue by andymlau** [steineggerlab/foldcomp#41]
Hi, 

Thanks for the great tool, just wanted to know if there's a way to merge two foldcomp databases?

e.g. merging the two below databases:
```
~/programs/foldcomp compress -t 8 --db batch_1
~/programs/foldcomp compress -t 8 --db batch_2

ls
batch_1  batch_1_db  batch_1_db.dbtype  batch_1_db.index  batch_1_db.lookup  batch_2  batch_2_db  batch_2_db.dbtype  batch_2_db.index  batch_2_db.lookup
```

Thanks in advance, 

Andy

**Comment by khb7840** [comment]
You can use [mmseqs2](https://github.com/soedinglab/MMseqs2) for manipulating foldcomp databases because foldcomp uses the same database format.

In this case, you can use `mmseqs concatdbs`.

`mmseqs concatdbs batch_1 batch2 batch_merged`

This command would work for merging databases.

**Comment by andymlau** [comment]
Many thanks!
