### ISSUE TITLE
Suggestion: Multi protein files

### ISSUE THREAD

**Issue by hmms117** [steineggerlab/foldcomp#5]
Hi

Very impressive compression performance - and *highly* relevant for anyone without 23Tb of space for 214mio structures 😀
A big issue with the current formats are the single-file-per-structure. If foldcomp could support compression and retrieval multiple protein structures - just like FASTA files for sequences - this could really make a big difference. 

Great work!

**Comment by martin-steinegger** [comment]
@hmms117 thank you for the kind words and for trying foldcomp. We are currently working on a tar version of the AlphaFold database (releasing it soon). It will reduce the file size of the database to about 1TB. This will be a single tar file; we will implement support to work with the tar file.

**Comment by hmms117** [comment]
Awesome Martin. Can’t wait to try it out!

Small note: .tar will certainly work, but I wonder if it is the most efficient file format to store and query potentially millions of structures. I’m not an expert, but perhaps it may be worth considering other formats known to have faster write/query performance (parquet, orc, json, etc).

**Comment by khb7840** [comment]
Thank you for your insightful suggestion. We chose to utilize `.tar` format first due to handling AlphaFold database in server side. We'll consider JSON and other formats for various use cases. Thanks again for your interest in our work! This really motivated us to improve `foldcomp`.

**Comment by hmms117** [comment]
That’s great to hear - if you manage to make it doable to work with millions of structures on a normal sized computer, I’m sure many will start using it. At least, Google and EMBL will appreciate the reduction in IO :)
